// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod into_base_uuid;
pub use into_base_uuid::IntoBaseUuid as IntoBaseUuidTrait;
pub mod into_entity_uuid;
pub use into_entity_uuid::IntoEntityUuid as IntoEntityUuidTrait;
