// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod base_uuid_wrapper;
pub use base_uuid_wrapper::BaseUuidWrapper as BaseUuidWrapperTrait;
pub mod into_base_uuid;
pub use into_base_uuid::IntoBaseUuid as IntoBaseUuidTrait;
pub mod into_chunk_plane_uuid;
pub use into_chunk_plane_uuid::IntoChunkPlaneUuid as IntoChunkPlaneUuidTrait;
pub mod into_entity_uuid;
pub use into_entity_uuid::IntoEntityUuid as IntoEntityUuidTrait;
