#![allow(dead_code)]
use convert_case::{Case, Casing};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
  // generate_macro_mod();
  // generate_list_mod_with_alias("src/chunk/map_builder/strategies", "Strategy");
  // generate_list_mod_with_alias("src/entity_id/_trait", "Trait");
  // generate_list_mod("src/entity_id/_type");
  // generate_list_mod("src/event/subscriber/_type");
  // generate_list_mod("src/game_state/_impl");
  // generate_list_mod_with_alias("src/game_state/_trait", "Trait");
  // generate_list_mod("src/game_state/_type");
  // generate_list_mod("src/lookup_service/_impl");
  // generate_list_mod_with_alias("src/lookup_service/_trait", "Trait");
  // generate_list_mod_with_alias("src/system", "System");
  // generate_list_mod_with_alias("src/system/_trait", "Trait");
}

fn generate_macro_mod() {
  let dir = Path::new("src/_macro/_list");
  let mut files = get_files_in_dir(dir);
  files.sort();
  let mut content = String::new();
  write_mod_header(&mut content);
  for file in &files {
    writeln!(content, "#[macro_use]\npub mod {};", file).expect("Failed to write to content string");
  }
  fs::write(dir.join("mod.rs"), content).expect("Failed to write mod.rs");
}

fn write_mod_header(content: &mut String) {
  writeln!(
    content,
    "// This file is automatically generated.\n// See <project_root>/build.rs for details.\n// Remember not to edit it manually."
  )
  .expect("Failed to write to content string");
}

fn generate_list_mod(base_dir: &str) {
  let path = format!("{}/_list", base_dir);
  let dir = Path::new(&path);
  let mut subdirs = get_subdirs_in_dir(dir);
  subdirs.sort();
  let mut content = String::new();
  write_mod_header(&mut content);
  for subdir in &subdirs {
    writeln!(content, "pub mod {};", subdir).expect("Failed to write to content string");
    writeln!(content, "pub use {}::*;", subdir).expect("Failed to write to content string");
  }
  fs::write(dir.join("mod.rs"), content).expect("Failed to write mod.rs");
}

fn generate_list_mod_with_alias(base_dir: &str, suffix: &str) {
  let path = format!("{}/_list", base_dir);
  let dir = Path::new(&path);
  let mut subdirs = get_subdirs_in_dir(dir);
  subdirs.sort();
  let mut content = String::new();
  write_mod_header(&mut content);
  for subdir in &subdirs {
    let struct_name = format!("{}{}", subdir.to_case(Case::UpperCamel), suffix);
    writeln!(content, "pub mod {};", subdir).expect("Failed to write to content string");
    writeln!(
      content,
      "pub use {}::{} as {};",
      subdir,
      subdir.to_case(Case::UpperCamel),
      struct_name
    )
    .expect("Failed to write to content string");
  }
  fs::write(dir.join("mod.rs"), content).expect("Failed to write mod.rs");
}

fn get_files_in_dir(dir: &Path) -> Vec<String> {
  fs::read_dir(dir)
    .unwrap_or_else(|_| panic!("Failed to read directory {:?}", dir))
    .filter_map(|e| {
      if let Ok(entry) = e {
        let path = entry.path();
        if path.extension()? == "rs" && path.file_stem()? != "mod" {
          return Some(path.file_stem()?.to_string_lossy().into_owned());
        }
      }
      None
    })
    .collect()
}

fn get_subdirs_in_dir(dir: &Path) -> Vec<String> {
  fs::read_dir(dir)
    .unwrap_or_else(|_| panic!("Failed to read directory {:?}", dir))
    .filter_map(|e| {
      if let Ok(entry) = e {
        let path = entry.path();
        if path.is_dir() {
          return Some(path.file_name()?.to_string_lossy().into_owned());
        }
      }
      None
    })
    .collect()
}
