//! The in-force decision index.

use crate::scan::decisions::{DecisionRecord, Status};
use std::collections::BTreeMap;

/// Render the decisions currently in force.
///
/// A wholly superseded decision does not appear — that absence is the point
/// (spec §4.3): a stale record left in the file WILL be found by a grepping
/// reader. A PARTIALLY superseded decision does appear, with the provisions
/// that survive, because it still governs them.
///
/// `scopes` maps a decision id to its surviving-provisions text and comes from
/// ASSERTED facts, never from parsing (spec §4.4): the trailing parenthetical
/// in a status line holds a rationale, a scope, or a date depending on the
/// decision, and those are not distinguishable syntactically.
pub fn index(records: &[DecisionRecord], scopes: &BTreeMap<String, String>) -> String {
    let mut sorted: Vec<&DecisionRecord> = records.iter().collect();
    sorted.sort_by(|a, b| a.id.cmp(&b.id));

    let mut out = String::from(
        "# Decisions in force\n\n\
         GENERATED by `digest render decisions` — do not edit. Wholly \
         superseded decisions are absent by design; git holds them.\n\n",
    );
    for r in sorted {
        match (r.status, scopes.get(&r.id).map(String::as_str)) {
            (Status::Superseded, None) => continue,
            (Status::Superseded, Some(scope)) => {
                let by = r.superseded_by.as_deref().unwrap_or("?");
                out.push_str(&format!(
                    "- **{}** {} — *partly superseded by {}; still in force: {}*\n",
                    r.id, r.title, by, scope
                ));
            }
            (Status::Proposed, _) => {
                out.push_str(&format!(
                    "- **{}** {} — *proposed, not ratified*\n",
                    r.id, r.title
                ));
            }
            (Status::Accepted, _) => {
                out.push_str(&format!("- **{}** {}\n", r.id, r.title));
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scan::decisions::{DecisionRecord, Status};

    fn rec(id: &str, title: &str, status: Status, by: Option<&str>) -> DecisionRecord {
        DecisionRecord {
            id: id.into(),
            title: title.into(),
            status,
            superseded_by: by.map(str::to_string),
        }
    }

    fn no_scopes() -> BTreeMap<String, String> {
        BTreeMap::new()
    }

    #[test]
    fn a_superseded_decision_falls_out_of_the_index() {
        let out = index(
            &[
                rec(
                    "0029",
                    "CI checks 500-seed censuses",
                    Status::Superseded,
                    Some("0063"),
                ),
                rec(
                    "0063",
                    "Census regen is local again",
                    Status::Accepted,
                    None,
                ),
            ],
            &no_scopes(),
        );
        assert!(
            !out.contains("0029"),
            "wholly superseded decisions must not appear"
        );
        assert!(out.contains("0063"));
    }

    #[test]
    fn a_partially_superseded_decision_stays_with_its_asserted_scope() {
        let mut scopes = BTreeMap::new();
        scopes.insert(
            "0026".to_string(),
            "for decision records; the study/chronicle/registry-row provisions stand".to_string(),
        );
        let out = index(
            &[rec(
                "0026",
                "Slugs, not numbers",
                Status::Superseded,
                Some("0043"),
            )],
            &scopes,
        );
        assert!(
            out.contains("0026"),
            "a partial supersession still governs in part"
        );
        assert!(
            out.contains("registry-row provisions stand"),
            "the surviving scope must be shown"
        );
        assert!(out.contains("0043"), "the superseder must be named");
    }

    #[test]
    fn a_superseded_decision_with_no_asserted_scope_is_dropped_even_if_its_file_had_a_parenthetical()
     {
        // 0029's status line carries a RATIONALE parenthetical and 0082's a
        // DATE. Neither is a scope, neither is asserted, so both must drop.
        let out = index(
            &[rec("0082", "A thing", Status::Superseded, Some("0099"))],
            &no_scopes(),
        );
        assert!(
            !out.contains("0082"),
            "absent scope means wholly superseded"
        );
    }

    #[test]
    fn proposed_decisions_are_marked_not_dropped() {
        let out = index(
            &[rec("0061", "A proposed thing", Status::Proposed, None)],
            &no_scopes(),
        );
        assert!(out.contains("0061"));
        assert!(out.to_lowercase().contains("proposed"));
    }
}
