//! Generated views. Every view is a pure function of the collection; none is
//! hand-edited. Regenerated by `scripts/regenerate-artifacts.sh` and
//! drift-checked with `git diff --exit-code`.

pub mod decisions;
pub mod delta;
pub mod doctor;
