//! Generated views. Every view is a pure function of the collection; none is
//! hand-edited. Regenerated by `scripts/regenerate-artifacts.sh` and
//! drift-checked with `git diff --exit-code`.

// NOTE: `pub mod doctor;` is added by Task 6 and `pub mod delta;` by Task 8,
// each alongside the file it creates. Declaring a module before its file
// exists does not compile.
pub mod decisions;
