//! Generated views. Every view is a pure function of the collection; none is
//! hand-edited. Regenerated by `scripts/regenerate-artifacts.sh` and
//! drift-checked with `git diff --exit-code`.

pub mod decisions;
pub mod doctor;
// NOTE: `pub mod delta;` is added by Task 8, alongside the file it creates.
// Declaring a module before its file exists does not compile.
