// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod no_op;
pub use no_op::NoOp as NoOpEvent;
pub mod quit;
pub use quit::Quit as QuitEvent;
