// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod room;
pub use room::*;
pub mod room_coordinates;
pub use room_coordinates::*;
pub mod room_factory;
pub use room_factory::*;
pub mod room_factory_strategy;
pub use room_factory_strategy::*;
pub mod room_lighting;
pub use room_lighting::*;
pub mod room_status;
pub use room_status::*;
pub mod room_temperature;
pub use room_temperature::*;
