// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod blank_fill;
pub use blank_fill::BlankFill as BlankFillStrategy;
pub mod compass_rose;
pub use compass_rose::CompassRose as CompassRoseStrategy;
