//! The committed audit report: deterministic tallies by class, crate, wave.

use crate::tag::{Verdict, parse_tag};
use crate::walk::CrateItems;
use std::collections::BTreeMap;

/// Render the full Markdown report for `crates` (deterministic, no timestamps).
pub fn render_report(crates: &[CrateItems]) -> String {
    let mut by_class: BTreeMap<String, u64> = BTreeMap::new();
    let mut by_wave: BTreeMap<u32, u64> = BTreeMap::new();
    // crate → (bare_ok, waiver, pending)
    let mut by_crate: BTreeMap<String, (u64, u64, u64)> = BTreeMap::new();

    for c in crates {
        let entry = by_crate.entry(c.crate_name.clone()).or_default();
        for item in &c.items {
            let verdicts = parse_tag(&item.doc).unwrap_or_default();
            for p in &item.positions {
                // The verdict covering this position: its own qualifier, else blanket.
                let v = verdicts
                    .iter()
                    .find(|v| position_of(v) == Some(p.name.as_str()))
                    .or_else(|| verdicts.iter().find(|v| position_of(v).is_none()));
                match v {
                    Some(Verdict::BareOk { class, .. }) => {
                        *by_class.entry(format!("bare-ok({class})")).or_default() += 1;
                        entry.0 += 1;
                    }
                    Some(Verdict::Waiver { .. }) => {
                        *by_class.entry("waiver".to_string()).or_default() += 1;
                        entry.1 += 1;
                    }
                    Some(Verdict::Pending { wave, .. }) => {
                        *by_class.entry("pending".to_string()).or_default() += 1;
                        *by_wave.entry(*wave).or_default() += 1;
                        entry.2 += 1;
                    }
                    None => {} // uncovered — a `check` error, not counted here
                }
            }
        }
    }

    let mut s = String::new();
    s.push_str("# Type Audit Report\n\n");
    s.push_str(
        "_Generated by `tools/type-audit`. Do not edit by hand; regenerate with\n\
         `cargo run --manifest-path tools/type-audit/Cargo.toml -- report`._\n\n",
    );

    s.push_str("## Verdicts by class\n\n| Class | Count |\n|-------|------:|\n");
    for (class, n) in &by_class {
        s.push_str(&format!("| {class} | {n} |\n"));
    }

    s.push_str("\n## By crate\n\n| Crate | bare-ok | waiver | pending | total |\n");
    s.push_str("|-------|--------:|-------:|--------:|------:|\n");
    for (name, (b, w, p)) in &by_crate {
        s.push_str(&format!("| {name} | {b} | {w} | {p} | {} |\n", b + w + p));
    }

    s.push_str("\n## Pending by wave\n\n| Wave | Count |\n|------|------:|\n");
    for (wave, n) in &by_wave {
        s.push_str(&format!("| wave-{wave} | {n} |\n"));
    }

    s
}

fn position_of(v: &Verdict) -> Option<&str> {
    match v {
        Verdict::BareOk { position, .. }
        | Verdict::Waiver { position, .. }
        | Verdict::Pending { position, .. } => position.as_deref(),
    }
}
