// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod is_a_chunk;
pub use is_a_chunk::IsAChunk as IsAChunkComponent;
pub mod is_a_chunk_plane;
pub use is_a_chunk_plane::IsAChunkPlane as IsAChunkPlaneComponent;
