//! The Earth-mask anchor (rift-and-fit spec §7): Earth's own coastline,
//! rasterized to the canonical L6 mesh, measured by the unchanged
//! estimator. The band proposal derives from THIS number and was
//! preregistered before the mask was built.
//!
//! Fixture regenerated by:
//!   cargo run --manifest-path tools/earth-mask/Cargo.toml --release \
//!     > book/src/laboratory/generated/earth-mask-l6/rows.csv

use hornvale_kernel::{CellMap, Geosphere, quantize};
use hornvale_terrain::GLOBE_LEVEL;
use hornvale_terrain::shape::shoreline_development_of_mask;
use std::path::Path;

/// `D_earth@L6`, measured once from the committed Earth-mask fixture and
/// pinned here, quantized to 8 significant digits ([`quantize`]'s
/// convention). This is Earth's own coastline — Natural Earth 110m land —
/// run through Hornvale's unchanged shoreline-development estimator; the
/// value this campaign's proposed band (`census-of-coasts-iv.md`, "The
/// Earth anchor") derives from.
const D_EARTH_L6: f64 = 8.2106747;

/// Load the committed `cell,land` fixture (ascending `CellId`) into a
/// `CellMap<bool>` sized to `geo`. Plain hand-rolled CSV parsing (two
/// columns, no quoting needed) rather than pulling in a CSV crate — this
/// is the same discipline the rest of the workspace uses for its own
/// generated-fixture readers.
fn load_land_mask(geo: &Geosphere, csv: &str) -> CellMap<bool> {
    let mut land_by_cell = vec![false; geo.cell_count()];
    for line in csv.lines().skip(1) {
        if line.is_empty() {
            continue;
        }
        let mut columns = line.split(',');
        let cell: u32 = columns
            .next()
            .expect("row has a cell column")
            .parse()
            .expect("cell column is a u32");
        let land: u8 = columns
            .next()
            .expect("row has a land column")
            .parse()
            .expect("land column is 0 or 1");
        land_by_cell[cell as usize] = land != 0;
    }
    CellMap::from_fn(geo, |c| land_by_cell[c.0 as usize])
}

#[test]
fn earth_mask_d_is_pinned() {
    // Fixture path relative to CARGO_MANIFEST_DIR: windows/lab is two
    // directories below the workspace root.
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../book/src/laboratory/generated/earth-mask-l6/rows.csv");
    let csv = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read Earth-mask fixture {}: {e}", path.display()));

    let geo = Geosphere::new(GLOBE_LEVEL);
    let land = load_land_mask(&geo, &csv);
    let d =
        shoreline_development_of_mask(&geo, &land).expect("Earth mask has land and a shoreline");

    // Sanity floor before pinning: Earth is not a circle.
    assert!(
        d > 1.5,
        "D_earth@L6 = {d} did not clear the sanity floor of 1.5"
    );

    let measured = quantize(d);
    assert_eq!(
        measured, D_EARTH_L6,
        "D_earth@L6 drifted: measured {measured} (raw {d}), pinned {D_EARTH_L6} — the mask \
         fixture or the estimator changed; regenerate deliberately and re-pin, don't paper over"
    );
}
