// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod actor_id;
pub use actor_id::*;
pub mod base_id;
pub use base_id::*;
pub mod chunk_id;
pub use chunk_id::*;
pub mod chunk_plane_id;
pub use chunk_plane_id::*;
pub mod chunk_seed_id;
pub use chunk_seed_id::*;
pub mod entity_id;
pub use entity_id::*;
pub mod object_id;
pub use object_id::*;
pub mod passage_id;
pub use passage_id::*;
pub mod player_id;
pub use player_id::*;
pub mod room_id;
pub use room_id::*;
