// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod event_publisher;
pub use event_publisher::EventPublisher as EventPublisherTrait;
