//! Background stars generated by fixed sky cell, never stored in genesis. // lexicon: equal-area sky region, not a mesh vertex
//! The legacy `starfield` API retains its original stream for version-one scenes.

use crate::streams;
use hornvale_kernel::Seed;
use hornvale_kernel::math;

use crate::neighborhood::CatalogStarId;
use crate::night_sky::StarObserver;
use crate::sky_position::EquatorialCoord;

/// Equal-area cells: twelve right-ascension sectors by four sine-declination bands. // lexicon: equal-area sky region, not a mesh vertex
/// type-audit: bare-ok(count)
/// plumb: pending(wave-1)
pub const SKY_CELL_COUNT: u16 = 48; // lexicon: equal-area sky region, not a mesh vertex

/// A validated, fixed-resolution sky cell. Resolution never depends on a query. // lexicon: equal-area sky region, not a mesh vertex
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct SkyCell(u16); // lexicon: equal-area sky region, not a mesh vertex

impl SkyCell /* lexicon: equal-area sky region, not a mesh vertex */ {
    /// Cell index in band-major order; out-of-range indices have no cell. // lexicon: equal-area sky region, not a mesh vertex
    /// type-audit: bare-ok(index: index)
    pub fn from_index(index: u16) -> Option<Self> {
        (index < SKY_CELL_COUNT).then_some(Self(index)) // lexicon: equal-area sky region, not a mesh vertex
    }

    /// All cells in canonical order, without generating any stars. // lexicon: equal-area sky region, not a mesh vertex
    pub fn all() -> impl Iterator<Item = Self> {
        (0..SKY_CELL_COUNT).map(Self) // lexicon: equal-area sky region, not a mesh vertex
    }
}

/// Identity of a background star, independent of visibility and traversal.
/// type-audit: bare-ok(index: ordinal)
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct BackgroundStarId {
    /// Astronomy seed, so an identity is scoped to its world.
    pub astronomy_seed: Seed,
    /// Fixed cell containing the star. // lexicon: equal-area sky region, not a mesh vertex
    pub cell: SkyCell, // lexicon: equal-area sky region, not a mesh vertex
    /// Draw ordinal within that cell, assigned before filtering. // lexicon: equal-area sky region, not a mesh vertex
    pub ordinal: u32,
}

/// Disjoint physical identities for modeled and background stars.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum StarId {
    /// A modeled neighbor's genesis identity.
    Catalog(CatalogStarId),
    /// A lazy background identity.
    Background(BackgroundStarId),
}

/// A physical star candidate in the query's equatorial frame.
/// type-audit: pending(wave-1: apparent_magnitude)
#[derive(Debug, Clone, PartialEq)]
pub struct SkyStar {
    /// Identity persists across observers and brightness cuts.
    pub id: StarId,
    /// Equatorial direction.
    pub position: EquatorialCoord,
    /// Apparent magnitude; smaller values are brighter.
    pub apparent_magnitude: f64,
}

/// Query a region expressed as cells; duplicates and traversal order are immaterial. // lexicon: equal-area sky region, not a mesh vertex
/// Only requested cells are generated. No simulation cache or roster is retained. // lexicon: equal-area sky region, not a mesh vertex
pub fn background_stars(
    astronomy_seed: Seed,
    cells: &[SkyCell], // lexicon: equal-area sky region, not a mesh vertex
    observer: &StarObserver,
) -> Vec<SkyStar> {
    let mut regions = cells.to_vec(); // lexicon: equal-area sky region, not a mesh vertex
    regions.sort_unstable();
    regions.dedup();
    let root = astronomy_seed.derive(streams::STARFIELD_CELLS); // lexicon: equal-area sky region, not a mesh vertex
    let mut stars = Vec::new();
    for region in regions {
        let label = region.0.to_string();
        let mut stream = root
            .derive(hornvale_kernel::seed::StreamLabel::dynamic(&label))
            .stream();
        let count = stream.range_u32(3, 6);
        for ordinal in 0..count {
            // Fixed draws, including invisible stars: observer detail cannot
            // change a later identity, position, or brightness.
            let sin_dec = -1.0 + (f64::from(region.0 / 12) + stream.next_f64()) / 2.0;
            let position = EquatorialCoord {
                dec_deg: math::asin(sin_dec).to_degrees(),
                ra_deg: (f64::from(region.0 % 12) + stream.next_f64()) * 30.0,
            };
            // Dim-heavy continuous magnitudes, including invisible candidates.
            // This is a declared statistical field, not a stellar lifecycle.
            let upper_magnitude = match stream.range_u32(1, 100) {
                1..=5 => 1.0,
                6..=15 => 2.0,
                16..=35 => 3.0,
                36..=65 => 4.0,
                66..=85 => 5.0,
                86..=95 => 6.0,
                _ => 7.0,
            };
            let apparent_magnitude = upper_magnitude - stream.next_f64();
            if observer.admits(apparent_magnitude, &position) {
                stars.push(SkyStar {
                    id: StarId::Background(BackgroundStarId {
                        astronomy_seed,
                        cell: region, // lexicon: equal-area sky region, not a mesh vertex
                        ordinal,
                    }),
                    position,
                    apparent_magnitude,
                });
            }
        }
    }
    stars
}

/// Compatibility brightness tier, with bright outliers and faint visible stars
/// clamped to the historical 1–5 range. Selection uses magnitude, never this tier.
pub(crate) fn magnitude_class(apparent_magnitude: f64) -> u8 {
    apparent_magnitude.ceil().clamp(1.0, 5.0) as u8
}

/// A faint background star: position and brightness class only. Class 1
/// is the brightest tier, 5 the faintest (dim-heavy, like a real sky).
/// type-audit: pending(wave-1: ra_deg), pending(wave-1: dec_deg), bare-ok(count: magnitude_class)
#[derive(Debug, Clone, PartialEq)]
pub struct FieldStar {
    /// Right ascension in degrees, [0, 360).
    pub ra_deg: f64,
    /// Declination in degrees, [-90, 90] (sphere-uniform).
    pub dec_deg: f64,
    /// Brightness class, 1 (brightest) ..= 5 (faintest).
    pub magnitude_class: u8,
}

/// Original full-sky projection for compatibility with `scene/neighbors/v1`.
/// Preserve count, draw order, positions and classes on the original stream.
/// New physical consumers request cells with [`background_stars`] and retain IDs. // lexicon: equal-area sky region, not a mesh vertex
pub fn starfield(astronomy_seed: Seed) -> Vec<FieldStar> {
    let mut stream = astronomy_seed.derive(streams::STARFIELD).stream();
    let count = stream.range_u32(100, 300);

    (0..count)
        .map(|_| {
            let dec_deg = math::asin(stream.next_f64() * 2.0 - 1.0).to_degrees();
            let ra_deg = stream.next_f64() * 360.0;
            let mag_roll = stream.range_u32(1, 100);
            let magnitude_class = match mag_roll {
                1..=5 => 1,
                6..=15 => 2,
                16..=35 => 3,
                36..=65 => 4,
                _ => 5,
            };
            FieldStar {
                ra_deg,
                dec_deg,
                magnitude_class,
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pins::SkyPins;
    use crate::system::generate;

    #[test]
    fn lazy_regions_are_repeatable_and_query_order_independent() {
        let seed = Seed(42).derive(streams::ROOT);
        let observer = StarObserver::default();
        let a = SkyCell::from_index(0).unwrap(); // lexicon: equal-area sky region, not a mesh vertex
        let b = SkyCell::from_index(25).unwrap(); // lexicon: equal-area sky region, not a mesh vertex
        let first = background_stars(seed, &[a], &observer);
        assert!(!first.is_empty());
        let other = background_stars(seed, &[b], &observer);
        assert!(!other.is_empty());
        assert_eq!(first, background_stars(seed, &[a], &observer));
        let mut joined = first.clone();
        joined.extend(other);
        assert_eq!(joined, background_stars(seed, &[b, a, b], &observer));
        assert_ne!(
            first,
            background_stars(Seed(43).derive(streams::ROOT), &[a], &observer)
        );
    }

    /// claim: structural(seed: 42) — iterates star candidates, not seeds;
    /// observer cuts select a stable subset of one physical sky.
    #[test]
    fn brightness_cuts_preserve_identities_and_never_admit_telescopic_stars() {
        let seed = Seed(42).derive(streams::ROOT);
        let cells: Vec<_> = SkyCell::all().collect(); // lexicon: equal-area sky region, not a mesh vertex
        let all = background_stars(seed, &cells, &StarObserver::default()); // lexicon: equal-area sky region, not a mesh vertex
        assert!(!all.is_empty());
        let observer = StarObserver {
            limiting_magnitude: 4.0,
            ..StarObserver::default()
        };
        let bright = background_stars(seed, &cells, &observer); // lexicon: equal-area sky region, not a mesh vertex
        assert!(!bright.is_empty() && bright.len() < all.len());
        assert_eq!(
            bright,
            all.iter()
                .filter(|s| s.apparent_magnitude <= 4.0)
                .cloned()
                .collect::<Vec<_>>()
        );
        let deep = StarObserver {
            limiting_magnitude: 30.0,
            ..StarObserver::default()
        };
        assert_eq!(all, background_stars(seed, &cells, &deep)); // lexicon: equal-area sky region, not a mesh vertex
        assert!(all.iter().all(|s| s.apparent_magnitude <= 6.0));
    }

    /// claim: structural(seed: 42) — iterates cells and stars, not seeds; // lexicon: equal-area sky region, not a mesh vertex
    /// one sky partitions spatially and is filtered without redrawing.
    #[test]
    fn regions_are_disjoint_and_horizon_filters_without_redrawing() {
        let seed = Seed(42).derive(streams::ROOT);
        let cells: Vec<_> = SkyCell::all().collect(); // lexicon: equal-area sky region, not a mesh vertex
        let all = background_stars(seed, &cells, &StarObserver::default()); // lexicon: equal-area sky region, not a mesh vertex
        assert!(!all.is_empty());
        for star in &all {
            let StarId::Background(id) = star.id else {
                panic!("background identity required")
            };
            let ra_sector = (star.position.ra_deg / 30.0).floor() as u16;
            let band = ((math::sin(star.position.dec_deg.to_radians()) + 1.0) * 2.0).floor() as u16;
            assert_eq!(id.cell, SkyCell::from_index(band * 12 + ra_sector).unwrap()); // lexicon: equal-area sky region, not a mesh vertex
        }
        let north = StarObserver {
            zenith: Some(EquatorialCoord {
                ra_deg: 0.0,
                dec_deg: 90.0,
            }),
            ..StarObserver::default()
        };
        assert_eq!(
            background_stars(seed, &cells, &north), // lexicon: equal-area sky region, not a mesh vertex
            all.into_iter()
                .filter(|s| s.position.dec_deg > 0.0)
                .collect::<Vec<_>>()
        );
        assert!(SkyCell::from_index(SKY_CELL_COUNT).is_none()); // lexicon: equal-area sky region, not a mesh vertex
        assert!(background_stars(seed, &[], &north).is_empty());
    }

    #[test]
    fn starfield_is_deterministic() {
        let seed = Seed(42).derive(streams::ROOT);
        let a = starfield(seed);
        let b = starfield(seed);
        assert_eq!(a, b);
    }

    #[test]
    fn starfield_count_is_in_range() {
        let seed = Seed(42).derive(streams::ROOT);
        let stars = starfield(seed);
        assert!((100..=300).contains(&stars.len()));
    }

    #[test]
    fn star_positions_are_valid() {
        let seed = Seed(42).derive(streams::ROOT);
        let stars = starfield(seed);
        for star in &stars {
            assert!(
                (-90.0..=90.0).contains(&star.dec_deg),
                "dec {} out of range",
                star.dec_deg
            );
            assert!(
                (0.0..360.0).contains(&star.ra_deg),
                "ra {} out of range",
                star.ra_deg
            );
            assert!((1..=5).contains(&star.magnitude_class));
        }
    }

    #[test]
    fn starfield_is_roughly_isotropic() {
        // Partition declination into six 30° bands and assert each is nonempty.
        // With sphere-uniform sampling and ≥100 stars, equatorial bands hold
        // most stars; polar bands ~3+ in expectation.
        let seed = Seed(42).derive(streams::ROOT);
        let stars = starfield(seed);

        let mut bands = [0; 6];
        for star in &stars {
            let band_idx = ((star.dec_deg + 90.0) / 30.0) as usize;
            if band_idx < 6 {
                bands[band_idx] += 1;
            }
        }

        for (i, &count) in bands.iter().enumerate() {
            assert!(
                count > 0,
                "band {} (dec [{}, {}]) has {} stars",
                i,
                -90.0 + i as f64 * 30.0,
                -90.0 + (i + 1) as f64 * 30.0,
                count
            );
        }
    }

    #[test]
    fn genesis_is_untouched_by_starfield() {
        // Calling starfield() must not consume any stream that genesis
        // reads. Generate two systems with the same seed, one preceded by
        // a starfield call; they must be byte-equal.
        let world_seed = Seed(42);

        // First generation: without starfield call.
        let system_a = generate(world_seed, &SkyPins::default()).expect("first generation failed");

        // Second generation: with a starfield call before it.
        let _stars = starfield(world_seed.derive(streams::ROOT));
        let system_b = generate(world_seed, &SkyPins::default()).expect("second generation failed");

        assert_eq!(system_a, system_b, "genesis was affected by starfield call");
    }
}
