// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod compass_rose;
pub use compass_rose::CompassRose as CompassRoseStrategy;
