// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod did_process_fn;
pub use did_process_fn::*;
pub mod should_process_fn;
pub use should_process_fn::*;
pub mod will_process_fn;
pub use will_process_fn::*;
