// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod game_state;
pub mod input_ready_flag;
pub mod output_queue;
pub mod quit_flag;
