//! # World
//!
//! `world` is tasked with creating and managing the actual game world.
//!
//! The Game World can be modeled as a directed graph **_G_ = (_V_, _E_)** where:
//!
//! - _V_ is a set of vertices, with each vertex _v_ ∈ _V_ representing a region
//!   in the game.
//! - _E_ is a set of edges, with each edge _e_ ∈ _E_ representing a passage
//!   between regions. An edge is an ordered pair (_v_<sub>_i_</sub>, _v_<sub>_j_</sub>)
//!   indicating a passage from region _v_<sub>_i_</sub> to region _v_<sub>_j_</sub>.
//!
//! ## World Seed
//!
//! Each world is generated by a distinct seed value, the **World Seed**, which
//! determines pseudorandom number generation through each of the subsequent
//! layers of the world structure. Specifics of this are implementation details.
//!
//! ### Graph Generation
//!
//! Vertices are generated on an infinite unit cartesian coordinate plane.
//!
//! The initial vertex is always generated at (0, 0). It is given a seed value,
//! a **Region Seed**, equal to that of the World Seed.
//!
//! We expand outward, adding new vertices, using a discretized version of
//! Bridson's algorithm.
//!
//! We connect the vertices in a minimum spanning tree using Prim's algorithm,
//! which seems to be well-suited to incremental growth.
//!
//! Then we add random cycles to ease navigation and enable player choice. This
//! is done by adding a random number of edges to the graph.
//!
//! This algorithm can easily generate more regions than anyone could explore,
//! but we can modify these algorithms to expand incrementally in the direction
//! of exploration.

/// Implementation of Bridson's algorithm.
pub mod bridson;
