//! The coverage report: what was walked, what was found, and what was skipped.
//!
//! **The denominator is the deliverable.** The campaign measured 610 numeric
//! constants across `domains/*/src` and `windows/*/src` with a line grep; this
//! tool parses instead, so it necessarily sees a different — larger — number,
//! and a report that printed only "N declared" would be unreconcilable against
//! either figure. So every constant the walk touched is accounted for in one of
//! four buckets: judged, undeclared, excluded as test-only, or excluded as
//! non-numeric. A scanner that silently walks less than a reader assumes is
//! this project's most-catalogued defect, and the only defence is arithmetic a
//! reader can check.

use crate::audit::{Judgement, judge};
use crate::walk::{AUDITED_ROOTS, KIND_MARKERS, NUMERIC_TYPES, Scan, Site};
use std::collections::BTreeMap;

/// Render the full Markdown coverage report (deterministic, no timestamps).
pub fn render_report(scan: &Scan) -> String {
    let mut s = String::new();
    s.push_str("# Plumb: authored-constant coverage\n\n");
    s.push_str(
        "_Generated by `tools/plumb`. Regenerate with\n\
         `cargo run --manifest-path tools/plumb/Cargo.toml -- report`._\n\n\
         Every authored numeric constant should declare **which axis it varies\n\
         along**. This report states the population it swept and what fraction\n\
         of it has been judged; it does not guess a rung for anything.\n\n",
    );

    // ---- scope -------------------------------------------------------------
    s.push_str("## Scope walked\n\n");
    s.push_str("| What | Value |\n|------|-------|\n");
    s.push_str(&format!(
        "| Roots | `{}` |\n",
        scan.roots
            .iter()
            .map(|p| p.display().to_string())
            .collect::<Vec<_>>()
            .join("`, `")
    ));
    s.push_str(&format!(
        "| Default roots | `{}` |\n",
        AUDITED_ROOTS.join("`, `")
    ));
    s.push_str(&format!("| Files parsed | {} |\n", scan.files_parsed));
    s.push_str(&format!(
        "| Constant types judged | `{}` |\n",
        NUMERIC_TYPES.join("`, `")
    ));
    s.push_str("| Directories pruned | `tests`, `examples`, `benches`, `target` |\n");
    s.push_str("| Visibility filter | none — a private `const` is audited like a `pub` one |\n");
    s.push_str(&format!(
        "| Kind-adjacency markers | `{}` |\n",
        KIND_MARKERS.join("`, `")
    ));
    s.push_str(
        "\n`kernel/` and `cli/` are outside the default roots and can be swept by\n\
         naming them explicitly (`plumb report kernel cli`).\n\n",
    );

    // ---- population --------------------------------------------------------
    let total = scan.consts.len();
    let mut by_site: BTreeMap<Site, usize> = BTreeMap::new();
    for c in &scan.consts {
        *by_site.entry(c.site).or_default() += 1;
    }

    s.push_str("## Population\n\n");
    s.push_str("| Bucket | Count |\n|--------|------:|\n");
    s.push_str(&format!(
        "| Numeric consts judged (the denominator) | {total} |\n"
    ));
    for (site, n) in &by_site {
        s.push_str(&format!("| … {} | {} |\n", site.label(), n));
    }
    s.push_str(&format!(
        "| Excluded: test-only (`#[cfg(test)]` / `#[test]`) | {} |\n",
        scan.test_only_consts
    ));
    s.push_str(&format!(
        "| Excluded: non-numeric type | {} |\n",
        scan.non_numeric_consts
    ));
    s.push_str(&format!(
        "| **Every `const` the walk touched** | **{}** |\n",
        total + scan.test_only_consts + scan.non_numeric_consts
    ));
    let file_level = by_site.get(&Site::File).copied().unwrap_or(0);
    s.push_str(&format!(
        "\nThe campaign's spec measured **610** with a line grep over the same two\n\
         roots. The comparable row here is `file-level`: **{file_level}**. The other\n\
         **{}** sit at whichever of the sites above are non-zero — every one an\n\
         authored number with an axis, and every one invisible to a scanner that\n\
         reads column 0. The two figures do not have to agree, and this table is\n\
         printed so that a reader can see exactly where they do not.\n\n",
        total - file_level
    ));

    // ---- coverage ----------------------------------------------------------
    let mut by_rung: BTreeMap<String, usize> = BTreeMap::new();
    let mut undeclared = 0usize;
    let mut malformed = 0usize;
    let mut kind_adjacent = 0usize;
    let mut kind_adjacent_declared = 0usize;
    // crate → (declared, undeclared, malformed)
    let mut by_crate: BTreeMap<String, (usize, usize, usize)> = BTreeMap::new();

    for c in &scan.consts {
        let entry = by_crate.entry(c.crate_name.clone()).or_default();
        let declared = match judge(c) {
            Judgement::Declared(rung) => {
                *by_rung.entry(rung.label()).or_default() += 1;
                entry.0 += 1;
                true
            }
            Judgement::Undeclared => {
                undeclared += 1;
                entry.1 += 1;
                false
            }
            Judgement::Malformed(_) => {
                malformed += 1;
                entry.2 += 1;
                false
            }
        };
        if c.kind_adjacent {
            kind_adjacent += 1;
            if declared {
                kind_adjacent_declared += 1;
            }
        }
    }

    s.push_str("## Coverage\n\n");
    s.push_str("| Verdict | Count |\n|---------|------:|\n");
    if by_rung.is_empty() {
        s.push_str("| _(no constant carries a `plumb:` tag yet)_ | 0 |\n");
    }
    for (rung, n) in &by_rung {
        s.push_str(&format!("| {rung} | {n} |\n"));
    }
    s.push_str(&format!("| **undeclared** | **{undeclared}** |\n"));
    s.push_str(&format!("| **malformed tag** | **{malformed}** |\n"));
    let declared = total - undeclared - malformed;
    s.push_str(&format!("| _total_ | {total} |\n"));
    s.push_str(&format!(
        "\nDeclared: **{declared} of {total}**. Undeclared is backlog; a malformed\n\
         tag is a defect.\n\n",
    ));

    // ---- the contested middle ---------------------------------------------
    s.push_str("## The contested middle\n\n");
    s.push_str(&format!(
        "{kind_adjacent} of the {total} constants sit in a file mentioning one of\n\
         the kind-adjacency markers above, across {} of the {} files parsed —\n\
         the creature-modelling middle where a rung is genuinely arguable, and\n\
         where `FATIGUE_RISE` lived. {kind_adjacent_declared} of them are declared.\n\n\
         **This is a reading aid, not a gate.** The markers are substrings, and\n\
         `Body` is shared with astronomy's celestial bodies, so the set is loose\n\
         in the inclusive direction on purpose.\n\n",
        scan.kind_adjacent_files, scan.files_parsed
    ));

    // ---- by crate ----------------------------------------------------------
    s.push_str("## By crate\n\n");
    s.push_str("| Crate | declared | undeclared | malformed | total |\n");
    s.push_str("|-------|---------:|-----------:|----------:|------:|\n");
    for (name, (d, u, m)) in &by_crate {
        s.push_str(&format!("| {name} | {d} | {u} | {m} | {} |\n", d + u + m));
    }

    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::walk::AuthoredConst;
    use std::path::PathBuf;

    fn c(name: &str, doc: &str, site: Site, kind_adjacent: bool) -> AuthoredConst {
        AuthoredConst {
            crate_name: "probe".into(),
            path: PathBuf::from("domains/probe/src/lib.rs"),
            line: 1,
            name: name.into(),
            ty: "f64".into(),
            doc: doc.into(),
            site,
            kind_adjacent,
        }
    }

    fn sample() -> Scan {
        Scan {
            roots: vec![PathBuf::from("domains"), PathBuf::from("windows")],
            files_parsed: 9,
            kind_adjacent_files: 2,
            consts: vec![
                c(
                    "A",
                    "plumb: universal(a lattice constant)",
                    Site::File,
                    false,
                ),
                c("B", "plumb: pending(wave-1)", Site::Module, true),
                c("C", "no tag", Site::FnBody, true),
                c("D", "plumb: universal", Site::Associated, false),
            ],
            test_only_consts: 11,
            non_numeric_consts: 5,
        }
    }

    /// The report must state the denominator and let a reader reconcile it: a
    /// judged count, every exclusion bucket, and a total that adds up. A
    /// scanner that walks less than a reader assumes is this project's
    /// most-catalogued defect, and this is the only thing that would show it.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3): delete the
    /// `push_str` that emits the `Every const the walk touched` row.
    ///
    /// ```text
    /// assertion failed: out.contains("| **Every `const` the walk touched** | **20** |")
    /// ```
    #[test]
    fn the_report_prints_a_reconcilable_denominator() {
        let out = render_report(&sample());
        assert!(out.contains("| Numeric consts judged (the denominator) | 4 |"));
        assert!(out.contains("| Excluded: test-only (`#[cfg(test)]` / `#[test]`) | 11 |"));
        assert!(out.contains("| Excluded: non-numeric type | 5 |"));
        // 4 judged + 11 test-only + 5 non-numeric = 20, and the row must say so.
        assert!(out.contains("| **Every `const` the walk touched** | **20** |"));
    }

    /// The site breakdown is what makes the parsed total reconcilable against
    /// the campaign's grep-measured 610, which could only see column 0.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3): delete the
    /// `for (site, n) in &by_site` loop that emits the per-site rows.
    ///
    /// ```text
    /// assertion failed: out.contains("| … file-level | 1 |")
    /// ```
    #[test]
    fn the_report_splits_the_population_by_declaration_site() {
        let out = render_report(&sample());
        assert!(out.contains("| … file-level | 1 |"));
        assert!(out.contains("| … in a nested mod | 1 |"));
        assert!(out.contains("| … associated (impl/trait) | 1 |"));
        assert!(out.contains("| … inside a fn body | 1 |"));
        assert!(out.contains("**610**"));
    }

    /// The scope is printed, not assumed. A reader must be able to see that
    /// `kernel` and `cli` were not walked without reading the source.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3): rename the row's
    /// label — `"| Roots | ..."` -> `"| _(roots omitted)_ | ..."`.
    ///
    /// ```text
    /// assertion failed: out.contains("| Roots | `domains`, `windows` |")
    /// ```
    #[test]
    fn the_report_prints_the_scope_it_walked() {
        let out = render_report(&sample());
        assert!(out.contains("| Roots | `domains`, `windows` |"));
        assert!(out.contains("| Files parsed | 9 |"));
        assert!(out.contains("`kernel/` and `cli/` are outside the default roots"));
        assert!(out.contains("Visibility filter | none"));
    }

    #[test]
    fn coverage_separates_declared_undeclared_and_malformed() {
        let out = render_report(&sample());
        assert!(out.contains("| universal | 1 |"));
        assert!(out.contains("| pending(wave-1) | 1 |"));
        assert!(out.contains("| **undeclared** | **1** |"));
        assert!(out.contains("| **malformed tag** | **1** |"));
        assert!(out.contains("Declared: **2 of 4**"));
    }

    #[test]
    fn the_contested_middle_is_reported_with_its_own_denominator() {
        let out = render_report(&sample());
        assert!(out.contains("2 of the 4 constants sit in a file mentioning"));
        assert!(out.contains("across 2 of the 9 files parsed"));
        assert!(out.contains("1 of them are declared"));
    }

    #[test]
    fn the_report_is_deterministic() {
        assert_eq!(render_report(&sample()), render_report(&sample()));
    }
}
