//! The coverage report: what was walked, what was found, and what was skipped.
//!
//! **The denominator is the deliverable.** The campaign measured 610 numeric
//! constants across `domains/*/src` and `windows/*/src` with a line grep; this
//! tool parses instead, so it necessarily sees a different — larger — number,
//! and a report that printed only "N declared" would be unreconcilable against
//! either figure. So every constant the walk touched is accounted for in one of
//! four buckets: judged, undeclared, excluded as test-only, or excluded as
//! non-numeric. A scanner that silently walks less than a reader assumes is
//! this project's most-catalogued defect, and the only defence is arithmetic a
//! reader can check.

use crate::audit::{Judgement, judge};
use crate::walk::{AUDITED_ROOTS, KIND_MARKERS, NON_QUANTITY_TYPES, SPEC_GREP_TYPES, Scan, Site};
use std::collections::BTreeMap;

/// Render the full Markdown coverage report (deterministic, no timestamps).
pub fn render_report(scan: &Scan) -> String {
    let mut s = String::new();
    s.push_str("# Plumb: authored-constant coverage\n\n");
    s.push_str(
        "_Generated by `tools/plumb`. Regenerate with\n\
         `cargo run --manifest-path tools/plumb/Cargo.toml -- report`._\n\n\
         Every authored constant should declare **which axis it varies\n\
         along**. This report states the population it swept and what fraction\n\
         of it has been judged; it does not guess a rung for anything.\n\n",
    );

    // ---- scope -------------------------------------------------------------
    s.push_str("## Scope walked\n\n");
    s.push_str("| What | Value |\n|------|-------|\n");
    s.push_str(&format!(
        "| Roots | `{}` |\n",
        scan.roots
            .iter()
            .map(|p| p.display().to_string())
            .collect::<Vec<_>>()
            .join("`, `")
    ));
    s.push_str(&format!(
        "| Default roots | `{}` |\n",
        AUDITED_ROOTS.join("`, `")
    ));
    s.push_str(&format!("| Files parsed | {} |\n", scan.files_parsed));
    s.push_str("| Constant types judged | every type except the non-quantities below |\n");
    s.push_str(&format!(
        "| Declared non-quantities | `{}`, plus containers (generic, array, tuple, reference) and markers |\n",
        NON_QUANTITY_TYPES.join("`, `")
    ));
    s.push_str("| Directories pruned | `tests`, `examples`, `benches`, `target` |\n");
    s.push_str("| Visibility filter | none — a private `const` is audited like a `pub` one |\n");
    s.push_str(&format!(
        "| Kind-adjacency markers | `{}` |\n",
        KIND_MARKERS.join("`, `")
    ));
    s.push_str(
        "\n`kernel/` and `cli/` are outside the default roots and can be swept by\n\
         naming them explicitly (`plumb report kernel cli`).\n\n",
    );

    // ---- population --------------------------------------------------------
    let total = scan.consts.len();
    let mut by_site: BTreeMap<Site, usize> = BTreeMap::new();
    for c in &scan.consts {
        *by_site.entry(c.site).or_default() += 1;
    }

    s.push_str("## Population\n\n");
    s.push_str("| Bucket | Count |\n|--------|------:|\n");
    s.push_str(&format!(
        "| Quantity consts judged (the denominator) | {total} |\n"
    ));
    for (site, n) in &by_site {
        s.push_str(&format!("| … {} | {} |\n", site.label(), n));
    }
    s.push_str(&format!(
        "| Excluded: test-only (`#[cfg(test)]` / `#[test]`) | {} |\n",
        scan.test_only_consts
    ));
    s.push_str(&format!(
        "| Excluded: declared non-quantity type | {} |\n",
        scan.non_quantity_consts()
    ));
    s.push_str(&format!(
        "| **Every `const` the walk touched** | **{}** |\n",
        total + scan.test_only_consts + scan.non_quantity_consts()
    ));
    let file_level = by_site.get(&Site::File).copied().unwrap_or(0);
    // The 610 comparison is only meaningful against the roots it was measured
    // over. On any other root set the sentence would print a true number beside
    // a figure it has nothing to do with, which is the exact shape this report
    // exists to avoid — so it is gated, not reworded.
    if walked_the_default_roots(scan) {
        // Two adjustments are needed before the spec's figure means anything
        // beside this one, and BOTH are on this side of the comparison: the
        // spec's grep saw only column 0, and only five primitive type names.
        let comparable = scan
            .consts
            .iter()
            .filter(|c| c.site == Site::File && SPEC_GREP_TYPES.contains(&c.ty.as_str()))
            .count();
        s.push_str(&format!(
            "\nThe campaign's spec measured **610** with a line grep over these same\n\
             two roots. That grep could see only column 0 and only the five names\n\
             `{}`, so the figure comparable to it is neither the denominator above\n\
             nor the whole `file-level` row — it is **{comparable}**: file-level\n\
             constants of those five types. The `file-level` row itself is\n\
             **{file_level}**, and the denominator is **{total}**; the difference is\n\
             what a line scanner restricted to five primitives cannot see. The two\n\
             figures do not have to agree, and this table is printed so that a\n\
             reader can see exactly where they do not.\n\n",
            SPEC_GREP_TYPES.join("`, `")
        ));
    } else {
        s.push_str(
            "\n**No comparison against the spec's 610 is printed here.** That figure\n\
             was measured over the default roots only, and this sweep walked a\n\
             different set, so the two populations are not the same population.\n\n",
        );
    }

    // ---- what was judged, by type ------------------------------------------
    let mut judged_types: BTreeMap<&str, usize> = BTreeMap::new();
    for c in &scan.consts {
        *judged_types.entry(c.ty.as_str()).or_default() += 1;
    }
    s.push_str("### Judged, by type\n\n");
    s.push_str(
        "Published for the same reason the exclusions below are: the denylist\n\
         decides this population, so a reader must be able to see a type it\n\
         admitted and disagree. A name here that is an identifier or a marker\n\
         rather than a quantity belongs in `NON_QUANTITY_TYPES`.\n\n",
    );
    s.push_str("| Type | Count |\n|------|------:|\n");
    for (label, n) in &judged_types {
        s.push_str(&format!("| `{label}` | {n} |\n"));
    }
    s.push('\n');

    // ---- what was excluded as a non-quantity -------------------------------
    if !scan.excluded_types.is_empty() {
        s.push_str("### Excluded as non-quantity, by type\n\n");
        s.push_str(
            "Listed rather than summed, because the denylist is a judgement and a\n\
             bare count would hide a quantity someone had wrongly denied.\n\n",
        );
        s.push_str("| Type | Count |\n|------|------:|\n");
        for (label, n) in &scan.excluded_types {
            s.push_str(&format!("| `{label}` | {n} |\n"));
        }
        s.push('\n');
    }

    // ---- coverage ----------------------------------------------------------
    let mut by_rung: BTreeMap<String, usize> = BTreeMap::new();
    let mut undeclared = 0usize;
    let mut malformed = 0usize;
    let mut kind_adjacent = 0usize;
    let mut kind_adjacent_declared = 0usize;
    // crate → (declared, undeclared, malformed)
    let mut by_crate: BTreeMap<String, (usize, usize, usize)> = BTreeMap::new();

    for c in &scan.consts {
        let entry = by_crate.entry(c.crate_name.clone()).or_default();
        let declared = match judge(c) {
            Judgement::Declared(rung) => {
                *by_rung.entry(rung.label()).or_default() += 1;
                entry.0 += 1;
                true
            }
            Judgement::Undeclared => {
                undeclared += 1;
                entry.1 += 1;
                false
            }
            Judgement::Malformed(_) => {
                malformed += 1;
                entry.2 += 1;
                false
            }
        };
        if c.kind_adjacent {
            kind_adjacent += 1;
            if declared {
                kind_adjacent_declared += 1;
            }
        }
    }

    s.push_str("## Coverage\n\n");
    s.push_str("| Verdict | Count |\n|---------|------:|\n");
    if by_rung.is_empty() {
        s.push_str("| _(no constant carries a `plumb:` tag yet)_ | 0 |\n");
    }
    for (rung, n) in &by_rung {
        s.push_str(&format!("| {rung} | {n} |\n"));
    }
    s.push_str(&format!("| **undeclared** | **{undeclared}** |\n"));
    s.push_str(&format!("| **malformed tag** | **{malformed}** |\n"));
    let declared = total - undeclared - malformed;
    s.push_str(&format!("| _total_ | {total} |\n"));
    s.push_str(&format!(
        "\nDeclared: **{declared} of {total}**. Undeclared is backlog; a malformed\n\
         tag is a defect.\n\n",
    ));

    // ---- the contested middle ---------------------------------------------
    s.push_str("## The contested middle\n\n");
    s.push_str(&format!(
        "{kind_adjacent} of the {total} constants sit in a file mentioning one of\n\
         the kind-adjacency markers above, across {} of the {} files parsed —\n\
         the creature-modelling middle where a rung is genuinely arguable, and\n\
         where `FATIGUE_RISE` lived. {kind_adjacent_declared} of them are declared.\n\n\
         **This is a reading aid, not a gate.** The markers are substrings, and\n\
         `Body` is shared with astronomy's celestial bodies, so the set is loose\n\
         in the inclusive direction on purpose.\n\n",
        scan.kind_adjacent_files, scan.files_parsed
    ));

    // ---- by crate ----------------------------------------------------------
    s.push_str("## By crate\n\n");
    s.push_str("| Crate | declared | undeclared | malformed | total |\n");
    s.push_str("|-------|---------:|-----------:|----------:|------:|\n");
    for (name, (d, u, m)) in &by_crate {
        s.push_str(&format!("| {name} | {d} | {u} | {m} | {} |\n", d + u + m));
    }

    s
}

/// True when this sweep walked exactly [`AUDITED_ROOTS`], in order.
///
/// Gates the one paragraph in this report that cites a figure measured over
/// those roots specifically. `report` accepts explicit roots (this tool's own
/// departure from `type-audit`), so the paragraph had a live way to go false.
pub fn walked_the_default_roots(scan: &Scan) -> bool {
    scan.roots.len() == AUDITED_ROOTS.len()
        && scan
            .roots
            .iter()
            .zip(AUDITED_ROOTS)
            .all(|(p, d)| p.as_os_str() == *d)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::walk::AuthoredConst;
    use std::path::PathBuf;

    fn c(name: &str, doc: &str, site: Site, kind_adjacent: bool) -> AuthoredConst {
        AuthoredConst {
            crate_name: "probe".into(),
            path: PathBuf::from("domains/probe/src/lib.rs"),
            line: 1,
            name: name.into(),
            ty: "f64".into(),
            doc: doc.into(),
            site,
            kind_adjacent,
        }
    }

    fn sample() -> Scan {
        Scan {
            roots: vec![PathBuf::from("domains"), PathBuf::from("windows")],
            files_parsed: 9,
            kind_adjacent_files: 2,
            consts: vec![
                c(
                    "A",
                    "plumb: universal(a lattice constant)",
                    Site::File,
                    false,
                ),
                c("B", "plumb: pending(wave-1)", Site::Module, true),
                c("C", "no tag", Site::FnBody, true),
                c("D", "plumb: universal", Site::Associated, false),
            ],
            test_only_consts: 11,
            excluded_types: [("&str".to_string(), 3), ("Option<…>".to_string(), 2)]
                .into_iter()
                .collect(),
        }
    }

    /// The report must state the denominator and let a reader reconcile it: a
    /// judged count, every exclusion bucket, and a total that adds up. A
    /// scanner that walks less than a reader assumes is this project's
    /// most-catalogued defect, and this is the only thing that would show it.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3): delete the
    /// `push_str` that emits the `Every const the walk touched` row.
    ///
    /// ```text
    /// assertion failed: out.contains("| **Every `const` the walk touched** | **20** |")
    /// ```
    #[test]
    fn the_report_prints_a_reconcilable_denominator() {
        let out = render_report(&sample());
        assert!(out.contains("| Quantity consts judged (the denominator) | 4 |"));
        assert!(out.contains("| Excluded: test-only (`#[cfg(test)]` / `#[test]`) | 11 |"));
        assert!(out.contains("| Excluded: declared non-quantity type | 5 |"));
        // 4 judged + 11 test-only + 5 non-numeric = 20, and the row must say so.
        assert!(out.contains("| **Every `const` the walk touched** | **20** |"));
    }

    /// The site breakdown is what makes the parsed total reconcilable against
    /// the campaign's grep-measured 610, which could only see column 0.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3): delete the
    /// `for (site, n) in &by_site` loop that emits the per-site rows.
    ///
    /// ```text
    /// assertion failed: out.contains("| … file-level | 1 |")
    /// ```
    #[test]
    fn the_report_splits_the_population_by_declaration_site() {
        let out = render_report(&sample());
        assert!(out.contains("| … file-level | 1 |"));
        assert!(out.contains("| … in a nested mod | 1 |"));
        assert!(out.contains("| … associated (impl/trait) | 1 |"));
        assert!(out.contains("| … inside a fn body | 1 |"));
        assert!(out.contains("**610**"));
    }

    /// The scope is printed, not assumed. A reader must be able to see that
    /// `kernel` and `cli` were not walked without reading the source.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3): rename the row's
    /// label — `"| Roots | ..."` -> `"| _(roots omitted)_ | ..."`.
    ///
    /// ```text
    /// assertion failed: out.contains("| Roots | `domains`, `windows` |")
    /// ```
    #[test]
    fn the_report_prints_the_scope_it_walked() {
        let out = render_report(&sample());
        assert!(out.contains("| Roots | `domains`, `windows` |"));
        assert!(out.contains("| Files parsed | 9 |"));
        assert!(out.contains("`kernel/` and `cli/` are outside the default roots"));
        assert!(out.contains("Visibility filter | none"));
    }

    /// **The 610 comparison is gated on the roots it was measured over.**
    /// `report` accepts explicit roots — this tool's own departure from
    /// `type-audit` — so `plumb report kernel cli` would otherwise print
    /// "the spec measured 610 with a line grep over these same two roots"
    /// directly beside `| Roots | kernel, cli |`.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3,
    /// fix round 1): make `walked_the_default_roots` return `true`
    /// unconditionally.
    ///
    /// ```text
    /// a figure measured over other roots must not be printed beside this one
    /// ```
    #[test]
    fn the_610_comparison_is_printed_only_for_the_default_roots() {
        // A second file-level constant, of a type the spec's grep could NOT
        // match, so the two restrictions produce two different numbers. With
        // only `sample()`'s single file-level `f64` both figures are 1 and the
        // assertion below could not tell them apart.
        let mut with_newtype = sample();
        with_newtype.consts.push(AuthoredConst {
            ty: "TickSpan".into(),
            ..c("REST_BOUT", "no tag", Site::File, false)
        });
        let default = render_report(&with_newtype);
        assert!(default.contains("**610**"));
        // Doubly restricted: column 0 AND one of the five grep-able names.
        assert!(default.contains("it is **1**: file-level"));
        assert!(default.contains("The `file-level` row itself is\n**2**"));
        assert!(default.contains("the denominator is **5**"));
        assert!(
            default.contains("| `TickSpan` | 1 |"),
            "a newtype is judged"
        );

        let mut elsewhere = with_newtype;
        elsewhere.roots = vec![PathBuf::from("kernel"), PathBuf::from("cli")];
        let out = render_report(&elsewhere);
        assert!(out.contains("| Roots | `kernel`, `cli` |"));
        assert!(
            !out.contains("**610**"),
            "a figure measured over other roots must not be printed beside this one"
        );
        assert!(out.contains("**No comparison against the spec's 610 is printed here.**"));
    }

    /// A single-root sweep is not the default set either, even though one of
    /// its roots matches — the check is on the whole list, not on membership.
    #[test]
    fn a_partial_root_set_is_not_the_default_root_set() {
        let mut one = sample();
        one.roots = vec![PathBuf::from("domains")];
        assert!(!walked_the_default_roots(&one));
        let mut swapped = sample();
        swapped.roots = vec![PathBuf::from("windows"), PathBuf::from("domains")];
        assert!(!walked_the_default_roots(&swapped));
        assert!(walked_the_default_roots(&sample()));
    }

    /// Non-quantity exclusions are published as a reviewable list, not summed
    /// into one opaque number: the denylist is a judgement, and a bare count
    /// would hide a quantity someone had wrongly denied.
    ///
    /// MUTATION THIS MUST FAIL AGAINST (confirmed 2026-09-02, The Plumb Task 3,
    /// fix round 1): delete the `Excluded as non-quantity, by type` block.
    ///
    /// ```text
    /// assertion failed: out.contains("| `&str` | 3 |")
    /// ```
    #[test]
    fn the_report_lists_every_non_quantity_exclusion_by_type() {
        let out = render_report(&sample());
        assert!(out.contains("### Excluded as non-quantity, by type"));
        assert!(out.contains("| `&str` | 3 |"));
        assert!(out.contains("| `Option<…>` | 2 |"));
        assert!(out.contains("| Excluded: declared non-quantity type | 5 |"));
    }

    #[test]
    fn coverage_separates_declared_undeclared_and_malformed() {
        let out = render_report(&sample());
        assert!(out.contains("| universal | 1 |"));
        assert!(out.contains("| pending(wave-1) | 1 |"));
        assert!(out.contains("| **undeclared** | **1** |"));
        assert!(out.contains("| **malformed tag** | **1** |"));
        assert!(out.contains("Declared: **2 of 4**"));
    }

    #[test]
    fn the_contested_middle_is_reported_with_its_own_denominator() {
        let out = render_report(&sample());
        assert!(out.contains("2 of the 4 constants sit in a file mentioning"));
        assert!(out.contains("across 2 of the 9 files parsed"));
        assert!(out.contains("1 of them are declared"));
    }

    #[test]
    fn the_report_is_deterministic() {
        assert_eq!(render_report(&sample()), render_report(&sample()));
    }
}
