//! The committed placement-audit roster: one section per shape-twin group,
//! deterministic, no timestamps — modeled on `tools/type-audit`'s report
//! house style.

use crate::detect::TwinGroup;
use crate::extract::TypeShape;
use crate::tag::{self, TagVerdict};

/// Render the full Markdown roster for `twins` (deterministic, no timestamps).
///
/// Ordering is inherited entirely from [`crate::detect::twins`] (groups and
/// each group's members are already sorted by `(crate_name, name)`), so this
/// function does no sorting of its own — there is nothing here that could
/// introduce nondeterminism.
pub fn render_report(twins: &[TwinGroup]) -> String {
    let mut s = String::new();
    s.push_str("# Placement Audit Roster\n\n");
    s.push_str(
        "_Generated by `tools/placement-audit`. Do not edit by hand; regenerate with\n\
         `cargo run --manifest-path tools/placement-audit/Cargo.toml -- report`._\n\n",
    );

    if twins.is_empty() {
        s.push_str("No shape twins found.\n");
        return s;
    }

    for (i, group) in twins.iter().enumerate() {
        let names: Vec<String> = group
            .members
            .iter()
            .map(|m| format!("`{}::{}`", m.crate_name, m.name))
            .collect();
        s.push_str(&format!("## Twin {}: {}\n\n", i + 1, names.join(" / ")));
        s.push_str("| Crate | Type | Location | Verdict | Shape |\n");
        s.push_str("|-------|------|----------|---------|-------|\n");
        for member in &group.members {
            let (verdict, shape) = describe(member);
            s.push_str(&format!(
                "| {} | {} | {}:{} | {} | {} |\n",
                member.crate_name,
                member.name,
                member.file.display(),
                member.line,
                verdict,
                shape,
            ));
        }
        s.push('\n');
    }

    s
}

/// Render a member's `(verdict, shape)` table entry from its parsed
/// `placement:` tag — `untagged` / `parse-error(...)` when there is no valid
/// adjudication to describe.
fn describe(member: &TypeShape) -> (String, String) {
    match tag::parse(&member.doc) {
        Ok(Some(parsed)) => {
            let verdict = match &parsed.verdict {
                TagVerdict::Promote(reason) => format!("promote({reason})"),
                TagVerdict::Deliberate(reason) => format!("deliberate({reason})"),
                TagVerdict::Deferred(reason) => format!("deferred({reason})"),
            };
            let shape = parsed.shape.unwrap_or_else(|| "\u{2014}".to_string());
            (verdict, shape)
        }
        Ok(None) => ("untagged".to_string(), "\u{2014}".to_string()),
        Err(e) => (format!("parse-error({e})"), "\u{2014}".to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::extract::ShapeKind;
    use std::path::PathBuf;

    fn shape(crate_name: &str, name: &str, doc: &str) -> TypeShape {
        TypeShape {
            crate_name: crate_name.to_string(),
            name: name.to_string(),
            kind: ShapeKind::Enum,
            members: vec!["Bright".to_string(), "Dim".to_string()],
            doc: doc.to_string(),
            file: PathBuf::from(format!("domains/{crate_name}/src/lib.rs")),
            line: 3,
        }
    }

    #[test]
    fn no_twins_renders_the_house_preamble_and_says_so() {
        let report = render_report(&[]);
        assert!(report.starts_with("# Placement Audit Roster\n"));
        assert!(report.contains("_Generated by `tools/placement-audit`"));
        assert!(report.contains("No shape twins found."));
    }

    #[test]
    fn a_deliberate_tagged_twin_renders_its_verdict_and_shape() {
        let group = TwinGroup {
            members: vec![
                shape(
                    "a",
                    "Mood",
                    "placement: deliberate(kept apart) shape(a1b2c3)",
                ),
                shape(
                    "b",
                    "Temper",
                    "placement: deliberate(kept apart) shape(a1b2c3)",
                ),
            ],
        };
        let report = render_report(&[group]);
        assert!(report.contains("deliberate(kept apart)"));
        assert!(report.contains("a1b2c3"));
        assert!(report.contains("`a::Mood`"));
        assert!(report.contains("`b::Temper`"));
    }

    #[test]
    fn an_untagged_member_renders_as_untagged() {
        let group = TwinGroup {
            members: vec![shape("a", "Mood", ""), shape("b", "Temper", "")],
        };
        let report = render_report(&[group]);
        assert!(report.contains("| untagged |"));
    }
}
