// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod advance_flag;
pub use advance_flag::AdvanceFlag as AdvanceFlagResource;
pub mod input_ready_flag;
pub use input_ready_flag::InputReadyFlag as InputReadyFlagResource;
pub mod output;
pub use output::Output as OutputResource;
pub mod player;
pub use player::Player as PlayerResource;
pub mod quit_flag;
pub use quit_flag::QuitFlag as QuitFlagResource;
pub mod random;
pub use random::Random as RandomResource;
pub mod seed_string;
pub use seed_string::SeedString as SeedStringResource;
pub mod tick;
pub use tick::Tick as TickResource;
