// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod into_actor_id;
pub use into_actor_id::IntoActorId as IntoActorIdTrait;
pub mod into_base_id;
pub use into_base_id::IntoBaseId as IntoBaseIdTrait;
pub mod into_chunk_id;
pub use into_chunk_id::IntoChunkId as IntoChunkIdTrait;
pub mod into_chunk_plane_id;
pub use into_chunk_plane_id::IntoChunkPlaneId as IntoChunkPlaneIdTrait;
pub mod into_chunk_seed_id;
pub use into_chunk_seed_id::IntoChunkSeedId as IntoChunkSeedIdTrait;
pub mod into_entity_id;
pub use into_entity_id::IntoEntityId as IntoEntityIdTrait;
pub mod into_object_id;
pub use into_object_id::IntoObjectId as IntoObjectIdTrait;
pub mod into_passage_id;
pub use into_passage_id::IntoPassageId as IntoPassageIdTrait;
pub mod into_player_id;
pub use into_player_id::IntoPlayerId as IntoPlayerIdTrait;
pub mod into_room_id;
pub use into_room_id::IntoRoomId as IntoRoomIdTrait;
