// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod into_actor_id;
pub use into_actor_id::IntoActorId as IntoActorIdTrait;
pub mod into_base_id;
pub use into_base_id::IntoBaseId as IntoBaseIdTrait;
pub mod into_entity_id;
pub use into_entity_id::IntoEntityId as IntoEntityIdTrait;
pub mod into_player_id;
pub use into_player_id::IntoPlayerId as IntoPlayerIdTrait;
pub mod into_room_id;
pub use into_room_id::IntoRoomId as IntoRoomIdTrait;
