// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod actor_lookup;
pub use actor_lookup::ActorLookup as ActorLookupTrait;
pub mod chunk_lookup;
pub use chunk_lookup::ChunkLookup as ChunkLookupTrait;
pub mod chunk_plane_lookup;
pub use chunk_plane_lookup::ChunkPlaneLookup as ChunkPlaneLookupTrait;
pub mod entity_lookup;
pub use entity_lookup::EntityLookup as EntityLookupTrait;
pub mod object_lookup;
pub use object_lookup::ObjectLookup as ObjectLookupTrait;
pub mod player_lookup;
pub use player_lookup::PlayerLookup as PlayerLookupTrait;
pub mod room_lookup;
pub use room_lookup::RoomLookup as RoomLookupTrait;
