name: "Post-Checkout"
description: "Performs common operations after checking out the codebase."
inputs: {}
runs:
  using: "composite"
  steps:

    - name: Update local toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy,rustfmt
        targets: wasm32-unknown-unknown

    - name: Rust cache
      uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update;
        sudo apt-get install -y \
          libasound2-dev \
          portaudio19-dev \
          build-essential \
          libpulse-dev \
          libdbus-1-dev \
          libudev-dev \
          ;

    - name: Toolchain info
      shell: bash
      run: |
        cargo --version --verbose;
        rustc --version;
        cargo clippy --version;

    - name: Build (Debug)
      shell: bash
      run: cargo build  --workspace --bins --examples --tests --verbose;

    - name: Build (Release)
      shell: bash
      run: cargo build --release --workspace --bins --examples --tests --verbose;
