// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod input;
pub use input::Input as InputSystem;
pub mod output;
pub use output::Output as OutputSystem;
