// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod command_queue;
pub use command_queue::CommandQueue as CommandQueueTrait;
pub mod game_state;
pub use game_state::GameState as GameStateTrait;
pub mod input_queue;
pub use input_queue::InputQueue as InputQueueTrait;
pub mod input_ready_flag;
pub use input_ready_flag::InputReadyFlag as InputReadyFlagTrait;
pub mod output_queue;
pub use output_queue::OutputQueue as OutputQueueTrait;
pub mod quit_flag;
pub use quit_flag::QuitFlag as QuitFlagTrait;
pub mod tick_counter;
pub use tick_counter::TickCounter as TickCounterTrait;
