// This file is automatically generated.
// See <project_root>/build.rs for details.
// Remember not to edit it manually.
pub mod no_op;
pub use no_op::NoOp as NoOpEffect;
pub mod set_diegetic_flag;
pub use set_diegetic_flag::SetDiegeticFlag as SetDiegeticFlagEffect;
pub mod set_input_ready_flag;
pub use set_input_ready_flag::SetInputReadyFlag as SetInputReadyFlagEffect;
pub mod set_quit_flag;
pub use set_quit_flag::SetQuitFlag as SetQuitFlagEffect;
