name: Code Coverage
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Post-Checkout Actions
        uses: ./.github/actions/post-checkout

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@1eda5d19daf935cb04d43ac3bb1b761ec2c8d8f8 # v2.33.8
        with:
          tool: cargo-llvm-cov@0.5.27

      - name: Generate code coverage
        run: |
          cargo llvm-cov \
            --all-features \
            --workspace \
            --lcov \
            --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
