name: Book

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Post-Checkout
        uses: ./.github/actions/post-checkout

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: |
          cargo build \
            --release \
            --target wasm32-unknown-unknown

      - name: Generate bindings
        run: |
          wasm-bindgen \
            ./target/wasm32-unknown-unknown/release/hornvale.wasm \
            --out-dir ./html/ \
            --no-typescript

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/book/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
